// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Explains telecom concepts in simple terms.
 *
 * - explainTelecomConcept - A function that explains a telecom concept.
 * - ExplainTelecomConceptInput - The input type for the explainTelecomConcept function.
 * - ExplainTelecomConceptOutput - The return type for the explainTelecomConcept function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainTelecomConceptInputSchema = z.object({
  concept: z.string().describe('The telecom concept to explain.'),
});
export type ExplainTelecomConceptInput = z.infer<typeof ExplainTelecomConceptInputSchema>;

const ExplainTelecomConceptOutputSchema = z.object({
  explanation: z.string().describe('A simple explanation of the telecom concept.'),
});
export type ExplainTelecomConceptOutput = z.infer<typeof ExplainTelecomConceptOutputSchema>;

export async function explainTelecomConcept(input: ExplainTelecomConceptInput): Promise<ExplainTelecomConceptOutput> {
  return explainTelecomConceptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainTelecomConceptPrompt',
  input: {schema: ExplainTelecomConceptInputSchema},
  output: {schema: ExplainTelecomConceptOutputSchema},
  prompt: `You are AI Nanban, a helpful assistant in the Indian context. Explain the following telecom concept in simple terms:\n\nConcept: {{{concept}}}`,
});

const explainTelecomConceptFlow = ai.defineFlow(
  {
    name: 'explainTelecomConceptFlow',
    inputSchema: ExplainTelecomConceptInputSchema,
    outputSchema: ExplainTelecomConceptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
